name: Build

on: [ push ]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: make vgm2opm

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: vgm2opm-${{ runner.os }}-${{ github.sha }}
        path: vgm2opm.exe
